# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
ratio       = [1, 2, 3]

[preview]
max_width       = 3000
max_height      = 3000

[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR", block = true, for = "unix" },
	{ run = "nvim %s",    block = true, desc = "nvim",           for = "windows" },
	{ run = "nvim -w %s", block = true,  desc = "nvim (block)",   for = "windows" },
]
