#!/usr/bin/env bash

# convert *.ipynb file to *.py

if [[ $# -eq 0 ]]; then
  read -p "To convert all .ipynb to .py recursively, type \"convert\": "
  if [[ "$REPLY" == "convert" ]]; then
    find . -type f -name '*.ipynb' -exec jupytext --set-formats ipynb,py {} +
  fi
else
  jupytext --set-formats ipynb,py "$@"
fi
