#!/bin/bash

# convert all *.py file to *.ipynb

read -p "To convert all .py to .ipynb recursively, type \"convert\": " input

if [[ "${input}" == "convert" ]]; then
  find . -type f -name '*.py' -exec jupytext --to notebook {} +
fi
