#!/bin/bash

# convert all *.py file to *.ipynb

if [[ $# -eq 0 ]]; then
  read -p "To convert all .py to .ipynb recursively, type \"convert\": "

  if [[ "$REPLY" == "convert" ]]; then
    find . -type f -name '*.py' -exec jupytext --to notebook {} +
  fi
else
  jupytext --to notebook "$@"
fi
