#!/usr/bin/env bash

DataAnalysisModules="pandas numpy matplotlib jupytext notebook pynvim selenium"
OcrModules="pytesseract pillow pynvim"
PdfModules="PyPDF2 pynvim pdfplumber"

# test if python has been installed
function checkPyPath() {
  printf "Seeking python binary..."
  if [[ -f "/bin/python3" ]]; then
    PY="python3"
    printf "Found: python3\n"
  elif [[ -f "/bin/python" ]]; then
    PY="python"
    printf "Found: python"
  else
    printf "Python not installed\n"
    exit 1
  fi
}

# check if target directory is given
function checkArguments() {
  if [[ -z "$1" ]]; then
    printf "Directory not set, use default: DataAnalysis\n"
    venvDir="DataAnalysis"
  else
    venvDir="$1"
  fi
}

function installModules() {
  # activate venv
  printf "Activating venv..."
  source "$HOME/.venv/$venvDir/bin/activate"
  printf "Success\n"

  # check if pypi installed
  printf "Seeking pypi binary..."
  if [[ ! -f "/bin/pip" ]]; then
    printf "Pypi not installed\n"
    exit 4
  fi
  printf "Found: pip\n"

  # install data analysis module
  printf "Start installing %s module..." "$venvDir"
  pip install $1 &> /dev/null
  printf "Complete\n"

  # exit venv
  deactivate
}

# initialization venv directory
function initVenv() {
  [[ ! -d "$HOME/.venv" ]] && mkdir "$HOME/.venv"
  
  $PY -m venv "$HOME/.venv/$venvDir"

  if [[ "$venvDir" == "DataAnalysis" ]]; then
    installModules "$DataAnalysisModules"
  elif [[ "$venvDir" == "OCR" ]]; then
    installModules "$OcrModules"
  elif [[ "$venvDir" == "PDF" ]]; then
    installModules "$PdfModules"
  fi

  printf "venv: %s Initialization complete\n" "$venvDir"
}

function main() {
  checkPyPath
  checkArguments "$@"
  initVenv
}

main "$@"
